SimpleDjangoTodoTemplate/urls.py
from django.contrib import admin
from django.urls import path, include

import todoapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todoapp.urls'))
]

todoapp/urls.py
from django.urls import path

from todoapp import views

app_name = "todo"
urlpatterns = [
    path('', views.TodoList.as_view(), name='todo-list'),
    path('item/<int:pk>/', views.TodoItemView.as_view(), name='todo-item'),
    path('item/<int:pk>/delete/', views.TodoItemDeleteView.as_view(), name='todo-item-delete'),
    path('item/<int:pk>/create/', views.TodoItemCreateView.as_view(), name='todo-item-create'),
    path('item/<int:pk>/update/', views.TodoItemUpdateView.as_view(), name='todo-item-update'),
]

todoapp/models.py
from django.db import models
from django.urls import reverse


class TodoItem(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('todo:todo-list')

    def __str__(self):
        return self.title

todoapp/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView

from todoapp.models import TodoItem


class TodoList(ListView):
    model = TodoItem
    template_name = 'todoapp/todoitem_list.html'
    context_object_name = "todoItems"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class TodoItemView(DetailView):
    model = TodoItem

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class TodoItemDeleteView(DeleteView):
    model = TodoItem
    success_url = reverse_lazy('todo:todo-list')


class TodoItemCreateView(CreateView):
    model = TodoItem
    fields = ['title', 'description']


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    fields = ['title', 'description']

todoapp/templates/todoapp/todoitem_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TodoDetails</title>
</head>
<body>
    <h1>Detail Page</h1>
</body>
</html>

todoapp/templates/todoapp/todoitem_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TodoList</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'todoapp/style.css' %}">
</head>
<body>
    <h1 class="head">My Todo</h1>
    <div class="todo-container">
        {% for item in todoItems %}
            <div class="todo-items">
            <div class="todo-item-detail">
                <h2 class="title">{{ item.title }}</h2>
                <h4 class="description">{{ item.description }}</h4>
            </div>
            <div class="todo-del"><a href="{% url 'todo:todo-item-delete' item.pk %}">X</a></div>
            </div>
        {% endfor %}
    </div>
</body>
</html>